### ISSUE TITLE
segmenter

### ISSUE THREAD

**Issue by krisbulman** [brightcove/zencoder_m3uzi#1]
I see this reads and writes m3u8 files, what is used to segment audio/video?

**Comment by jgreer** [comment]
Segmenting is a separate process, and generally done with Apple's mediafilesegmenter, or open source tools such as http://www.ioncannon.net/programming/452/iphone-http-streaming-with-ffmpeg-and-an-open-source-segmenter/

Zencoder uses custom proprietary software for segmenting.
