### ISSUE TITLE
Ssc sport

### ISSUE THREAD

**Issue by Belal133** [brightcove/zencoder_m3uzi#4]
Ssc 3
Ssc 4
Ssc 6
 No signal

**Comment by stoicAlchemist** [comment]
This looks like an automatically created issue, please re-open if you need something in particular

**Comment by Belal133** [comment]
Channel playback is not working

في الجمعة، ٢٢ يوليو ٢٠٢٢, ٥:٣٤ م Brian I. Martínez Estrada <
***@***.***> كتب:

**Comment by Belal133** [comment]
http://live.multies.net/category/sports-ch/ssc-sprot/

في الجمعة، ٢٢ يوليو ٢٠٢٢ ٦:٥٦ م Werl Bee ***@***.***> كتب:
